name: CI

on: [push]

jobs:
  build:
    name: Generate Github Page
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run gitpages
      - name: Deploy site to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
         repo-token: ${{ secrets.GH_PAT }}
         site-directory: docs
